### ISSUE TITLE
Restore CBA keybind functionality

### ISSUE THREAD

**Issue by ACyprus** [ACyprus/cyprus-quick-release-system#6]
**Situation**

I launched `cyp_quickrelease` back in mid 2014, alongside the early mechanisms for `CBA` keybinding. Since then, `CBA` has rewritten their keybinding system, deprecating the original functions and thus breaking the feature in `cyp_quickrelease`.

I never got around to patching this, and so the addon now feels 'crippled' for many players.

Default keybinds still work but cannot be configured in-game by the player.

**Tasks**

- [x] update the CBA calls to the current keybinding functions
- [x] reset distinct default keybind for each action
- [x] test on existing and new player profiles

**NB**

The aim is to release this update as `v1.2.0-rc1` prior to any other fixes or enhancements.
